MyBlog/MyBlog.WebUI/Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.ComponentModel.DataAnnotations;
using MyBlog.WebUI.Infrastructure;
using MyBlog.WebUI.Models;


namespace MyBlog.WebUI.Controllers
{

    /// <summary>
    /// Класс для работы с доступам к операциям на сайте
    /// </summary>
    [Authorize(Roles = "Administrators")]
    public class RoleAdminController : Controller
    {

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }

        //===================================вывод всех ролей=========================================

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }
        //====================================Создание роли===========================================
        public ActionResult Create()
        {
            return View();
        }
        //====================================создание роли POST-запрос==============
        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if(ModelState.IsValid)
            {
                IdentityResult result
                    = await RoleManager.CreateAsync(new AppRole(name));

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }

            }
            return View(name);
        }

        //=================================================Удаление роли=======================

            [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Роль не найдена" });
            }
        }

        //==============================Редактирование роли=====================================
        public async Task<ActionResult> Edit(string id)
        {
            AppRole role = await RoleManager.FindByIdAsync(id);
            string[] memberIDs = role.Users.Select(x => x.UserId).ToArray();

            IEnumerable<AppUser> members
                = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));

            IEnumerable<AppUser> nonMembers = UserManager.Users.Except(members);

            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        //===============================POST-запрос==========================================================

        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    result = await UserManager.AddToRoleAsync(userId, model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    result = await UserManager.RemoveFromRoleAsync(userId,
                    model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");

            }
            return View("Error", new string[] { "Роль не найдена" });
        }

        //============================================================================
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

MyBlog/MyBlog.WebUI/Views/RoleAdmin/Create.cshtml
@model string
@{
    ViewBag.Title = "Создание роли";
}

<h2>Создать роль</h2>
@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Название</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Создать</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

MyBlog/MyBlog.WebUI/Views/RoleAdmin/Edit.cshtml
@using MyBlog.WebUI.Models

@model RoleEditModel
@{
    ViewBag.Title = "Изменить роль";
}

<h2>Изменить роль</h2>
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <div class="panel panel-primary">
        <div class="panel-heading">Добавить в роль <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr>
                    <td colspan="2">Все пользователи в роли</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Добавить в роль</td>
                </tr>
                foreach (AppUser user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">Удалить из роли <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr>
                    <td colspan="2">Нет пользователей в роли</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Удалить из роли</td>
                </tr>
                foreach (AppUser user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

MyBlog/MyBlog.WebUI/Views/RoleAdmin/Index.cshtml
@using MyBlog.WebUI.Infrastructure;
@using MyBlog.WebUI.Models;
@model IEnumerable<AppRole>

@{
    ViewBag.Title = "Роли";

}


<div class="panel panel-primary">
    <div class="panel-heading">Roles</div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Пользователи</th>
            <th style="min-width: 150px"></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center">Нет ролей</td>
            </tr>
        }
        else
        {
            foreach (AppRole role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        @if (role.Users == null || role.Users.Count == 0)
                        {
                            @: Нет пользователей в этой роли
                    }
                        else
                        {
                            <p>
                                @string.Join(", ", role.Users.Select(x =>
                            Html.GetUserName(x.UserId)))
                        </p>
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                        {
                            @Html.ActionLink("Изменить", "Edit", new { id = role.Id },
                        new { @class = "btn btn-primary btn-xs", style = "float:left; margin-right:5px" })
                            <button class="btn btn-danger btn-xs" type="submit">Удалить</button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("Создать", "Create", null, new { @class = "btn btn-primary" })