MyBlog/MyBlog.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using MyBlog.WebUI.Infrastructure;
using Microsoft.AspNet.Identity;
using MyBlog.WebUI.Models;
using System.Threading.Tasks;



namespace MyBlog.WebUI.Controllers
{

    /// <summary>
    /// Класс отвечающий за создание создание/редактирования/удаления пользователей(только пользователь с ролью администратора может выполнить данные действия)
    /// </summary>
    [Authorize(Roles = "Administrators")]
    public class AdminController : Controller
    {
        /// <summary>
        /// Метод отвечающий за вывод всех пользователей(список пользователей)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }

        //===========================================================================================================
        /// <summary>
        /// Метод, отвечающий за создание новых пользователей(GET-запрос)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Метод, отвечающий за создание новых пользователей(POST-запрос)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Create(CreateModel model)
        {
            if(ModelState.IsValid)
            {
                AppUser user = new AppUser { UserName = model.Name, Email = model.Email };

                IdentityResult result = await UserManager.CreateAsync(user, model.Password);

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(model);
        }

        //============================================================================================================


            /// <summary>
            /// Метод, отвечающий за удаление пользователей из базы данных
            /// </summary>
            /// <param name="id"></param>
            /// <returns></returns>
            [HttpPost]
            public async Task<ActionResult> Delete(string id)
        {
            AppUser user = await UserManager.FindByIdAsync(id);

            if(user!=null)
            {
                IdentityResult result = await UserManager.DeleteAsync(user);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Пользователь не найден" });
            }

        }

        //============================================================================================================


            /// <summary>
            /// Метод, отвечающий за редактирования пользователей
            /// </summary>
            /// <param name="id"></param>
            /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            AppUser user = await UserManager.FindByIdAsync(id);
            if(user!=null)
            {
                return View(user);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public async Task<ActionResult> Edit(string id, string email, string password)
        {
            AppUser user = await UserManager.FindByIdAsync(id);
            if(user!=null)
            {
                user.Email = email;
                IdentityResult validEmail
                    = await UserManager.UserValidator.ValidateAsync(user);

                if(!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }

                IdentityResult validPass = null;
                if(password!=string.Empty)
                {
                    validPass = await UserManager.PasswordValidator.ValidateAsync(password);

                    if (validPass.Succeeded)
                    {
                        user.PasswordHash =
                            UserManager.PasswordHasher.HashPassword(password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }
                

                if ((validEmail.Succeeded && validPass == null) ||
                       (validEmail.Succeeded && password != string.Empty && validPass.Succeeded))
                {
                    IdentityResult result = await UserManager.UpdateAsync(user);
                    if(result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "Пользователь не найден");
            }

            return View(user);

           


        }



        //-----------------Метод для определения ошибки---------------
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        //-----------------------------------------------------------

        //--------------------доступ к контексту данных-----------------------
        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
        //--------------------------------------------------------------------
    }
}

MyBlog/MyBlog.WebUI/Views/Admin/Create.cshtml
@model MyBlog.WebUI.Models.CreateModel

@{
    ViewBag.Title = "Добавление пользователя";
}



@Html.ValidationSummary(false)

@using (Html.BeginForm())
{
    <div class="form-group">

        <label>Имя</label>
        @Html.TextBoxFor(x=>x.Name, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })

    </div>

    <div class="form-group">

        <label>Пороль</label>
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })

    </div>

    <button type="submit" class="btn btn-primary">Создать</button>

    @Html.ActionLink("Назад","Index",null, new { @class = "btn btn-default" })
}

MyBlog/MyBlog.WebUI/Views/Admin/Edit.cshtml
@model MyBlog.WebUI.Models.AppUser
@{
    ViewBag.Title = "Редактирование пользователя";
}

@Html.ValidationSummary(false)

<h2>Редактирование пользователя</h2>
<div class="form-group">
    <label>Id</label>
    <p class="form-control-static">@Model.Id</p>
</div>

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Id)
    <div class="form-group">
        <label>Имя</label>
        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Пароль</label>
        <input name="password" type="password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

MyBlog/MyBlog.WebUI/Views/Admin/Index.cshtml
@using MyBlog.WebUI.Models
@model IEnumerable<AppUser>

@{
    ViewBag.Title = "Индификация";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Учетные записи
    </div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Имя</th>
            <th>Email</th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3" class="text-center">Нет ни одной учетной записи</td>
            </tr>
        }
        else
        {
            foreach (AppUser user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td>
                        @using (Html.BeginForm("Delete", "Admin", new { id = user.Id }))
                        {
                            @Html.ActionLink("Изменить", "Edit", new { id = user.Id },
                            new { @class = "btn btn-primary btn-xs", style = "float: left; margin-right: 10px" })
                            <button class="btn btn-danger btn-xs" type="submit">Удалить</button>
                        }
                    </td>

                </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("Создать", "Create", null, new { @class = "btn btn-primary" })