MyBlog/MyBlog.WebUI/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyBlog.WebUI.Models;
using MyBlog.Domain.Entities;
using MyBlog.WebUI.Infrastructure;
using System.Data.Entity;
using PagedList;
using System.IO;
using System.Data.Entity.Infrastructure;
using System.Net;

namespace MyBlog.WebUI.Controllers
{
    /// <summary>
    /// Контроллер отвечающий за работу со статьями
    /// </summary>
    public class PostController : Controller
    {
        AppIdentityDbContext dbpost;

        public PostController()
        {
            dbpost = new AppIdentityDbContext();
        }

        #region Вывод отдельной статьи с текстом
        //============================================================================================================
        //==================================================<основная страница статьи>=========================================================
        [ValidateInput(false)]
        public ActionResult Postdesc(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            else
            {
                Post post = dbpost.posts.Find(id);
                return View(post);
            }

        }

        //===========================================================================================================
        #endregion


        #region Список категорий со статьями
        // ====================================<Вывод списка категорий>===============================================
        /// <summary>
        /// Метод вывода списка категорий
        /// </summary>
        /// <returns></returns>
        public ActionResult ListCategory()
        {
            var catpost = dbpost.categoryPosts;
            return View(catpost.ToList());
        }
        //============================================================================================================
        #endregion

        #region Статьи из выбранной категории
        //========================================<Выводим статьи по выбранной категории c пагинацией>=============================
        /// <summary>
        /// Метод просмотра статей по выбранной категории
        /// </summary>
        /// <param name="id"> Индификатор выбранной категории</param>
        /// <param name="page">Переменная для постраничного вывода</param>
        /// <returns></returns>
        public ActionResult ViewCatSelect(int? id,int? page)
        {
            if(id==null)
            {
                return HttpNotFound();
            }
            else
            {
                var catSel = dbpost.categoryPosts.Include(c=>c.posts).FirstOrDefault(c=>c.CategoryID==id);
                ViewBag.CatID =id;
                int pageSize = 6;
                int pageNumber = (page ?? 1);

                return View(catSel.posts.ToPagedList(pageNumber,pageSize));
            }
        }


        #endregion

        #region Панель редактирования Категорий
        //======================================<Панель редактирования статей>=======================================
        /// <summary>
        /// Метод управления Статей
        /// </summary>
        /// <param name="sortOrder">Выбор сортировки</param>
        /// <param name="searchString">Поисковой запрос</param>
        /// <param name="currentFilter">Выбарнный фильтр</param>
        /// <param name="page">Параметр для постраничного вывода</param>
        /// <returns></returns>
        [Authorize(Roles = "Administrators")]
        public ActionResult EditPannelPost(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            //если мы получаем пустую строку то динамический элемент  ViewBag.NameSortParm=name_des
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //если sortOrder равен Date ViewBag.DateSortParm=date_desc иначе ViewBag.DateSortParm=Date
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            //------------------------Пагинация--------------------------
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            //----------------------------------------------
            var post = from n in dbpost.posts.Include(c=>c.category)
                     select n;
            //если строка поиска не равна  нулю то производим выборку из базы данных по введенным ключам
            if (!String.IsNullOrEmpty(searchString))
            {
                post = post.Where(n => n.NamePost.Contains(searchString) || n.Author.Contains(searchString));


            }

            switch (sortOrder)
            {
                case "name_desc":                       //если sortOrder==name_desc сортировка по имени в порядке убывания
                    post = post.OrderByDescending(n => n.NamePost);
                    break;

                case "Date":                            //если sortOrder==Date сортировка по дате по возрастанию
                    post = post.OrderBy(n => n.DatePublic);
                    break;

                case "date_desc":                       //если sortOrder==date_desc сортировка по дате по убыванию
                    post = post.OrderByDescending(n => n.DatePublic);
                    break;

                default:                                //по умолчанию по имени по возрастанию
                    post = post.OrderBy(n => n.NamePost);
                    break;


            }

            //============================================ПАГИНАЦИЯ====================================================
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(post.ToPagedList(pageNumber, pageSize));
            //=========================================================================================================

        }
        #endregion

        #region Панель редактирования категорий
        //===================================================<Панель редактирования категорий к статьям>========================================================

        //======================================<Панель редактирования категорий>=======================================
        /// <summary>
        /// Метод управления категориями
        /// </summary>
        /// <param name="sortOrder">выбор сортировки</param>
        /// <param name="searchString">Поисковой запрос</param>
        /// <param name="currentFilter">Выбранный фильтр</param>
        /// <param name="page">Параметр для постраничного вывода</param>
        /// <returns></returns>
        [Authorize(Roles = "Administrators")]
        public ActionResult EditPannelCategory(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            //если мы получаем пустую строку то динамический элемент  ViewBag.NameSortParm=name_des
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.IDSortParm = sortOrder == "ID" ? "ID_desc" : "ID";

            //------------------------Пагинация--------------------------
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            //----------------------------------------------
            var cat = from c in dbpost.categoryPosts.Include(p=>p.posts)
                       select c;
            //если строка поиска не равна  нулю то производим выборку из базы данных по введенным ключам
            if (!String.IsNullOrEmpty(searchString))
            {
                cat = cat.Where(c => c.NameCategory.Contains(searchString));


            }

            switch (sortOrder)
            {
                case "name_desc":                       //если sortOrder==name_desc сортировка по имени в порядке убывания
                    cat = cat.OrderByDescending(n => n.NameCategory);
                    break;
                case "ID":
                    cat = cat.OrderBy(n => n.CategoryID);
                    break;
                case "ID_desc":
                    cat = cat.OrderByDescending(n => n.CategoryID);
                    break;



                default:                                //по умолчанию по имени по возрастанию
                    cat = cat.OrderBy(n => n.NameCategory);
                    break;


            }

            //============================================ПАГИНАЦИЯ====================================================
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(cat.ToPagedList(pageNumber, pageSize));
            

        }

        //===========================================================================================================

        #endregion
        //++++++++++++++++++++++++++++++++++++++<CRUD-операции>++++++++++++++++++++++++++++++++++++++++++++++++++++++

        #region Создание новой статьи
        //==================================<Создание новой статьи>==============================================
        /// <summary>
        /// Get-метод создания нового объекта статей
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ViewResult CreatePost()
        {
            PopulateCategoryDropDownList();
            return View();
        }
        /// <summary>
        /// POST-метод обработки запроса со страницы CreatePost
        /// </summary>
        /// <param name="npost">Новый объект статей</param>

MyBlog/MyBlog.WebUI/Views/Post/CreateCategory.cshtml
@using MyBlog.Domain.Entities
@model Category

@{
    ViewBag.Title = "Добавить новую категорию для статей";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="text-center">
    <h2>Новая категория</h2>
</div>



@using (Html.BeginForm("CreatePost", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Статья</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        

        <div class="form-group">
            @Html.LabelFor(model => model.NameCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameCategory, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 10, 45, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })

            </div>

        </div>
      
        <div class="form-group">
            @Html.LabelFor(model => model.NameImageCat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameImageCat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameImageCat, "", new { @class = "text-danger" })

            </div>

        </div>
        <div class="form-group">
            <div class="control-label col-md-2"><p>Файл изображения</p></div>
            <div class="form-control">
                <input type="file" name="uploadImage" />
            </div>

        </div>

        <div class="form-group">
            @foreach (Post c in ViewBag.Posts)
            {
                <input type="checkbox" name="selectedCourses" value="@c.PostID"
                       @(Model.posts.Contains(c) ? "checked=\"checked\"" : "") />@c.NamePost <br />
            }
        </div>
       



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "EditPannelCategory")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MyBlog/MyBlog.WebUI/Views/Post/CreatePost.cshtml
@model MyBlog.Domain.Entities.Post
@{
    ViewBag.Title = "Создание новой статьи";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="text-center">
    <h2>Новая статья</h2>
</div>

@using (Html.BeginForm("CreatePost", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Статья</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        

        <div class="form-group">
            @Html.LabelFor(model => model.NamePost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamePost, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descriptionPost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.descriptionPost, 10, 45, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.descriptionPost, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePublic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePublic, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(model => model.DatePublic, "", new { @class = "text-danger" })

            </div>

        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TextPost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TextPost, 10, 45, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TextPost, "", new { @class = "text-danger" })

            </div>

        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.NameImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameImage, "", new { @class = "text-danger" })

            </div>

        </div>
        <div class="form-group">
            <div class="control-label col-md-2"><p>Файл изображения</p></div>
            <div class="form-control">
                <input type="file" name="uploadImage" />
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "EditPannelPost")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{


    <script src="~/scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(function () {
            $(".datepicker").datepicker({ dateFormat: 'dd/mm/yy' });
        });
        $.datepicker.regional['ru'] = {
            closeText: 'Закрыть',
            prevText: 'Пред',
            nextText: 'След',
            currentText: 'Сегодня',
            monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
            'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
            'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            dayNames: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
            dayNamesShort: ['вск', 'пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт'],
            dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            weekHeader: 'Не',
            dateFormat: 'dd.mm.yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
        };
        $.datepicker.setDefaults($.datepicker.regional['ru']);
    </script>
}

MyBlog/MyBlog.WebUI/Views/Post/EditCategory.cshtml
@using MyBlog.Domain.Entities
@model Category
@{
    ViewBag.Title = "Редактирование категории статей";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="text-center">
    <h2>Изменение категории</h2>
</div>



@using (Html.BeginForm("CreatePost", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CategoryID)
    <div class="form-horizontal">
        <h4>Статья</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        <div class="form-group">
            @Html.LabelFor(model => model.NameCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameCategory, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 10, 45, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })

            </div>

        </div>
   
        <div class="form-group">
            @Html.LabelFor(model => model.NameImageCat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameImageCat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameImageCat, "", new { @class = "text-danger" })

            </div>

        </div>





        <div class="form-group">
            <div class="control-label col-md-2"><p>Файл изображения</p></div>
            <div class="form-control">
                <input type="file" name="uploadImage" />
            </div>

        </div>



        <div class="form-group text-center">
            <p>Список статей</p>
            @foreach (Post c in ViewBag.Posts)
            {
                <input type="checkbox" name="selectedCourses" value="@c.PostID"
                       @(Model.posts.Contains(c) ? "checked=\"checked\"" : "") />@c.NamePost <br />
            }

        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "EditPannelPost")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MyBlog/MyBlog.WebUI/Views/Post/EditPannelCategory.cshtml
@model PagedList.IPagedList<MyBlog.Domain.Entities.Category>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Панель редактирования категорий";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="text-center">
    <h2>Панель редактирования категорий</h2>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-10">
            @using (Html.BeginForm("EditPannelCategory", "Post", FormMethod.Get))
            {
                <p>
                    Поиск по имени: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Поиск" />
                </p>
            }

            <table class="table">
                <tr>
                    <th>
                        @Html.ActionLink("Индификатор", "EditPannelCategory", new { sortOrder = ViewBag.NameSortParm })
                    </th>

                    <th>
                        @Html.ActionLink("Название статьи", "EditPannelCategory", new { sortOrder = ViewBag.IDSortParm })
                    </th>
                    <th>
                        <p>Описание</p>
                    </th>

                    

                    <th>
                        <p>Включенные статьи</p>
                    </th>

                    <th>
                        <p>Название картинки в заголовке</p>
                    </th>

                    <th>
                        <p>Картинка</p>
                    </th>

                </tr>



                @foreach(var cat in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelitem=>cat.CategoryID)
                        </td>
                        <td>
                            @Html.ActionLink(cat.NameCategory,"EditCategory",new {id=cat.CategoryID })
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => cat.description)
                        </td>
                        <td>
                            @{ 
                                foreach(var psts in cat.posts )
                                {
                                    <ul>
                                        <li>
                                            @psts.NamePost
                                        </li>
                                    </ul>
                                    <br />
                                }
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem=>cat.NameImageCat)
                        </td>
                       
                         <td>
                             @Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
        + Convert.ToBase64String(cat.ImageMainCat) + "\" />")
                        </td>
                        <td>

                            @Html.ActionLink("Предварительный просмотр", "DetailPost", new { id = cat.CategoryID }) |
                            @Html.ActionLink("удалить", "Delete", new { id = cat.CategoryID })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>





<div class="container text-center">
    <div class="row">
        Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("EditPannelCategory", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>


</div>

MyBlog/MyBlog.WebUI/Views/Post/EditPannelPost.cshtml
@model PagedList.IPagedList<MyBlog.Domain.Entities.Post>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Панель редактирования статей";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="text-center">
    <h2>Панель редактирования</h2>
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                @using (Html.BeginForm("EditPannelPost", "Post", FormMethod.Get))
            {
                    <p>
                        @Html.ActionLink("Создать новую статью", "CreatePost", null, new {@class="btn btn-primmary"})
                        Поиск по имени: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
                        <input type="submit" value="Поиск" />
                    </p>
                }

                <table class="table">
                    <tr>
                        <th>
                            <p>Индификатор</p>
                        </th>

                        <th>
                            @Html.ActionLink("Название статьи", "EditPannelPost", new { sortOrder = ViewBag.NameSortParm })
                        </th>

                        <th>
                            <p>Автор статьи</p>
                        </th>

                        <th>
                            <p>Описание</p>
                        </th>

                        <th>
                            <p>Основной текст статьи</p>

                        </th>

                        <th>
                            <p>Категория статьи</p>
                        </th>

                        <th>

                            @Html.ActionLink("Время публикации", "EditPannelPost", new { sortOrder = ViewBag.DateSortParm })
                        </th>

                        <th>
                            <p>Название картинки в заголовке</p>
                        </th>

                        <th>
                            <p>Картинка</p>
                        </th>

                    </tr>


                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelitem=>item.PostID)
                            </td>
                            <td>
                                @Html.ActionLink(item.NamePost,"EditPost",new {id=item.PostID },null)
                               
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem=>item.Author)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem=>item.descriptionPost)
                            </td>

                            <td>
                                @Html.DisplayTextFor(modelitem=>item.TextPost)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem=>item.category.NameCategory)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem=>item.DatePublic)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem=>item.NameImage)
                            </td>
                            <td>
                                @Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
        + Convert.ToBase64String(item.ImageMainPost) + "\" />")
                            </td>

                            <td>

                                @Html.ActionLink("Предварительный просмотр", "DetailPost", new { id = item.PostID }) |
                                @Html.ActionLink("удалить", "Delete", new { id = item.PostID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<br />

<div class="container">
   <div class="row">

       <div class="col-md-4">
           @Html.ActionLink("Панель редактирования категорий", "EditPannelCategory", null, new {@class="btn btn-primary" })
       </div>
   </div>

</div>
<div class="container text-center">
    <div class="row">
        Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("EditPannelPost", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>


</div>

MyBlog/MyBlog.WebUI/Views/Post/ListCategory.cshtml
@model IEnumerable<MyBlog.Domain.Entities.Category>
@{
    ViewBag.Title = "Список категорий";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <h2>Список категорий</h2>
</div>

<div class="container">
    @foreach (var item in Model)
    {
        <div class="row">
            <div class="well">
                <h3>@item.NameCategory</h3>
                <div class="col-md-6">
                    @Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
        + Convert.ToBase64String(item.ImageMainCat) + "\" />")
                </div>
                <div class="col-md-6">
                    @item.description
                </div>
                
                <div class="text-right">
                    <li>@Html.ActionLink("Подробнее", "ViewCatSelect", "Post", new { id = item.CategoryID }, new { @class = "btn btn-primary" })</li>
                </div>


            </div>
        </div>
    }
</div>
<br />